Fix: JSON parsing error is shown when deleting account
privacybydesign/irma_keyshare_webclient pull request #55
Opened 2024-04-18 15:51 UTC by ivard

2024-04-18 16:40 UTC, imre-sidn commented
Same issue as the one fixed in https://github.com/privacybydesign/irma_keyshare_webclient/pull/43

2024-04-18 16:41 UTC, imre-sidn approved these changes

2024-04-18 16:43 UTC, imre-sidn requested changes
as you mentioned @ivard, the current fix breaks revalidate mail error flow

2024-04-18 19:13 UTC, ivard commented
> as you mentioned @ivard, the current fix breaks revalidate mail error flow

Fixed it in the same manner as #43 .

2024-04-19 06:38 UTC, bobhageman approved these changes

2024-04-19 09:42 UTC, merged